"""The store protocol.

A store holds the Notion mirror, the pipeline's intermediate results, and the patch
ledger. It persists and retrieves; it does not decide anything. Every judgement is made
by the modules above it, which take plain values and neither know nor care where they
came from — that is what keeps `import palimpsest` usable with no database at all
beyond the default SQLite file.

Two implementations ship. **SQLite** is the default: `sqlite3` is in the standard
library, the whole mirror is one file you can copy or delete, and for a personal
knowledge base of a few thousand blocks it is not merely adequate but faster than the
network round-trip it replaces. **Postgres/Supabase** is the same schema for when the
review UI is deployed and more than one process writes.
"""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from palimpsest.store.stats import StoreStats
from palimpsest.types import Claim, Judgement, Patch, Source

__all__ = ["Store", "StoreStats", "open_store"]


@runtime_checkable
class Store(Protocol):
    """Persistence for the mirror, the pipeline and the ledger."""

    # -- the Notion mirror -----------------------------------------------------

    def put_pages(self, pages: list[dict]) -> int: ...
    def put_blocks(self, blocks: list[dict]) -> int: ...
    def put_links(self, links: list[tuple[str, str, str | None]]) -> int: ...
    def get_page(self, page_id: str) -> dict | None: ...
    def get_pages(self, limit: int | None = None) -> list[dict]: ...
    def get_blocks(self, page_id: str | None = None,
                   limit: int | None = None) -> list[dict]: ...
    def get_block(self, block_id: str) -> dict | None: ...
    def backlinks(self, page_id: str) -> list[str]: ...
    def set_page_profile(self, page_id: str, role: str, summary: str,
                         topics: list[str]) -> None: ...
    def page_last_synced(self) -> dict[str, str]: ...
    def drop_missing(self, seen_page_ids: set[str]) -> int: ...

    # -- the pipeline ----------------------------------------------------------

    def put_source(self, source: Source) -> str: ...
    def get_source(self, source_id: str) -> Source | None: ...
    def find_source_by_hash(self, content_hash: str) -> Source | None: ...
    def list_sources(self, limit: int = 50) -> list[dict]: ...
    def put_claims(self, claims: list[Claim]) -> int: ...
    def get_claims(self, source_id: str) -> list[Claim]: ...
    def put_judgements(self, judgements: list[Judgement]) -> int: ...

    # -- the ledger ------------------------------------------------------------

    def put_patch(self, patch: Patch) -> str: ...
    def get_patch(self, patch_id: str) -> Patch | None: ...
    def list_patches(self, status: str | None = None, limit: int = 50) -> list[dict]: ...
    def set_patch_status(self, patch_id: str, status: str, reviewer: str | None = None,
                         notes: str | None = None) -> None: ...
    def record_applied_op(self, patch_id: str, op: Any, page_id: str | None) -> None: ...
    def mark_op_reverted(self, op_id: str) -> None: ...
    def put_provenance(self, rows: list[dict]) -> int: ...
    def provenance_for_block(self, block_id: str) -> list[dict]: ...
    def page_history(self, page_id: str, limit: int = 200) -> list[dict]: ...

    # -- records ---------------------------------------------------------------

    def put_record(self, kind: str, payload: dict, label: str = "") -> int: ...
    def get_records(self, kind: str | None = None, limit: int = 50) -> list[dict]: ...

    # -- schema and health -----------------------------------------------------

    def migrate(self) -> list[str]: ...
    def applied_migrations(self) -> list[str]: ...
    def ping(self) -> float: ...
    def stats(self) -> StoreStats: ...
    def truncate_all(self) -> None: ...
    def close(self) -> None: ...


def open_store(url: str = "sqlite:///palimpsest.db") -> Store:
    """Open a store from a URL.

    `sqlite:///path/to.db` (or `sqlite://:memory:`) and `postgresql://user:pass@host/db`
    are understood. Supabase connection strings are Postgres URLs, so they work
    unchanged. Credentials come from the URL or the environment, never a source file.
    """
    if url.startswith("sqlite"):
        from palimpsest.store.sqlite import SQLiteStore

        path = url.split("://", 1)[1].lstrip("/") or ":memory:"
        return SQLiteStore(path)
    if url.startswith(("postgres://", "postgresql://")):
        from palimpsest.store.postgres import PostgresStore

        return PostgresStore(url)
    raise ValueError(f"unrecognised store URL {url!r}; use sqlite:// or postgresql://")
